// src/ui/react/components/ViewModelRenderer.js
import React, { useCallback } from 'react'
import { TemperatureEditor } from './TemperatureEditor'

export function ViewModelRenderer (props) {
  const { vm } = props

  return (
    <React.Fragment>
      <TemperatureEditor
        key="air"
        value={vm.air.value}
        units={vm.air.units}
        onValueChange={useCallback(value => vm.air.intentions.setValue({ value }), ['air'])}
        onUnitsChange={useCallback(units => vm.air.intentions.setUnits({ units }), ['air'])}
      />
      <TemperatureEditor
        key="water"
        value={vm.water.value}
        units={vm.water.units}
        onValueChange={useCallback(value => vm.water.intentions.setValue({ value }), ['water'])}
        onUnitsChange={useCallback(units => vm.water.intentions.setUnits({ units }), ['water'])}
      />
    </React.Fragment>
  )
}

// src/ui/lit-html/components/ViewModelRenderer.js
import { html } from 'lit-html'
import { TemperatureEditor } from './TemperatureEditor'

export const ViewModelRenderer = (props) => {
  const { vm } = props

  return html`
    <h2>lit-html ViewModelRenderer</h2>
    ${TemperatureEditor({
      value: vm.air.value,
      units: vm.air.units,
      onValueChange: value => vm.air.intentions.setValue({ value }),
      onUnitsChange: units => vm.air.intentions.setUnits({ units })
    })}
    ${TemperatureEditor({
      value: vm.water.value,
      units: vm.water.units,
      onValueChange: value => vm.water.intentions.setValue({ value }),
      onUnitsChange: units => vm.water.intentions.setUnits({ units })
    })}
  `
}
